version: '3.8'

services:
 your_service_name:
    build: .
    environment:
      - "ROS_DOMAIN_ID=42"
    volumes:
      - ./src:/src
    network_mode: "host"
    ipc: host
    pid: host
    privileged: true
    stdin_open: true
    tty: true